export const Currencies = [
    { key: 'BTC', value: 'BTC', text: 'Bitcoin' },
    { key: 'ETC', value: 'ETC', text: 'Ethereum' },
    { key: 'LTC', value: 'LTC', text: 'Litcoin' },
    { key: 'TRX', value: 'TRX', text: 'TRON' },
    { key: 'XVG', value: 'XVG', text: 'Verge' },
    { key: 'ICX', value: 'ICX', text: 'ICON' },
    { key: 'ADA', value: 'ADA', text: 'Cardano' },
    { key: 'EOS', value: 'EOS', text: 'EOS' },
    { key: 'BCC', value: 'BCC', text: 'Bitconnect' },
    { key: 'ONT', value: 'ONT', text: 'Ontology' },
    { key: 'NANO', value: 'NANO', text: 'Nano' },
    { key: 'BNB', value: 'BNB', text: 'Binance Coin' },
    { key: 'XRP', value: 'XRP', text: 'Ripple' },
    { key: 'STORM', value: 'STORM', text: 'Storm' },
    { key: 'NEO', value: 'NEO', text: 'NEO' },
    { key: 'NCASH', value: 'NCASH', text: 'Nucleus Vision' },
    { key: 'XLM', value: 'XLM', text: 'Stellar' },
    { key: 'VEN', value: 'VEN', text: 'VeChain' },
    { key: 'WAN', value: 'WAN', text: 'WanChain' },
    { key: 'IOST', value: 'IOST', text: 'IOStoken' },
    { key: 'MIOTA', value: 'MIOTA', text: 'IOTA' },
    { key: 'SUB', value: 'SUB', text: 'Substratum' },
    { key: 'OMG', value: 'OMG', text: 'OmiseGO' },
    { key: 'ZRX', value: 'ZRX', text: '0x' },
    { key: 'LSK', value: 'LSK', text: 'Lisk' },
    { key: 'STRAT', value: 'STRAT', text: 'Stratis' },
    { key: 'WTC', value: 'WTC', text: 'Waltonchain' },
    { key: 'NEBL', value: 'NEBL', text: 'Neblio' },
    { key: 'MTL', value: 'MTL', text: 'Metal' },
    { key: 'ELF', value: 'ELF', text: 'aelf' },
    { key: 'QSP', value: 'QSP', text: 'Quantstamp' },
    { key: 'QTUM', value: 'QTUM', text: 'QTUM' },

]